#!/usr/bin/env bash
# scripts/token-metrics.sh
#
# 1-week POC metrics collector for the token-efficiency experiment
# (orchestration/token-efficiency/PLAN.md + RESULTS.md). Since Cursor's subscription doesn't expose
# a per-turn token meter, we snapshot the PROXIES that track tool usage + context size:
#   - Headroom compression savings (context-compressor.sh stats, raw + best-effort parse)
#   - artifacts the crons produced (daily blog / daily LLD / weekly timetable / solutions)
#   - cron activity today (log lines) and repo-freshness (last git-fetch-all run)
#
# Append one CSV row per day; render a weekly markdown report on demand.
#
# Usage:
#   token-metrics.sh                 # snapshot today -> append poc.csv (+ raw stats)
#   token-metrics.sh snapshot        # same
#   token-metrics.sh report          # render token-efficiency/metrics/WEEK-<isoweek>.md
set -eu

WORKSPACE="${WORKSPACE:-$HOME/Workspace}"
DEV_DIR="${SOFTWAREDEV_DIR:-$WORKSPACE/SoftwareDev}"
METRICS_DIR="$WORKSPACE/orchestration/token-efficiency/metrics"
RAW_DIR="$METRICS_DIR/raw"
CSV="$METRICS_DIR/poc.csv"
CC="$WORKSPACE/scripts/context-compressor.sh"
DATE="$(date +%Y-%m-%d)"
WEEK="$(date +%G-W%V)"
ACTION="${1:-snapshot}"

mkdir -p "$RAW_DIR"

count_today() {  # files under $1 modified today (mtime<1 day)
    local dir="$1"
    [ -d "$dir" ] || { echo 0; return; }
    find "$dir" -type f -mtime -1 2>/dev/null | wc -l | tr -d ' '
}

snapshot() {
    # --- Headroom savings (best-effort; docker may be down) ---
    local raw="$RAW_DIR/$DATE.stats.txt" hr_note="na"
    if [ -x "$CC" ] || [ -f "$CC" ]; then
        if bash "$CC" stats >"$raw" 2>&1; then
            # try to pull any "saved"/percentage/token number for a quick column
            hr_note="$(grep -Eio '([0-9.]+%|[0-9,]+ tokens?|saved[^,\n]*)' "$raw" 2>/dev/null | head -1 | tr ',' ' ' | tr -s ' ' || true)"
            [ -z "$hr_note" ] && hr_note="captured"
        else
            hr_note="stats-failed(docker down?)"
        fi
    fi

    local blogs lld tt_exists sol_total cron_runs
    blogs="$(count_today "$DEV_DIR/blogs/daily")"
    lld="$(count_today "$DEV_DIR/lld/daily")"
    [ -f "$WORKSPACE/learning-system/timetables/$WEEK.md" ] && tt_exists=1 || tt_exists=0
    sol_total="$(find "$DEV_DIR/lld/solutions" -type f ! -name README.md 2>/dev/null | wc -l | tr -d ' ')"
    cron_runs="$(grep -h "$(date +%Y-%m-%d)" "$WORKSPACE"/orchestration/logs/*.log 2>/dev/null | grep -c '=====' | tr -d ' ' || true)"
    [ -z "$cron_runs" ] && cron_runs=0

    if [ ! -f "$CSV" ]; then
        echo "date,week,hr_savings,blogs_today,lld_today,timetable_week,solutions_total,cron_runs_today" > "$CSV"
    fi
    # de-dupe: replace an existing row for today
    if grep -q "^$DATE," "$CSV" 2>/dev/null; then
        grep -v "^$DATE," "$CSV" > "$CSV.tmp" && mv "$CSV.tmp" "$CSV"
    fi
    echo "$DATE,$WEEK,\"$hr_note\",$blogs,$lld,$tt_exists,$sol_total,$cron_runs" >> "$CSV"
    echo "[token-metrics] snapshot $DATE -> $CSV"
    echo "  hr_savings=$hr_note blogs=$blogs lld=$lld timetable=$tt_exists solutions=$sol_total cron_runs=$cron_runs"
    echo "  raw headroom stats: $raw"

    # real transcript-based token trend (free; no LLM/API cost)
    local trend="$WORKSPACE/orchestration/token-efficiency/scripts/token-trend.py"
    [ -f "$trend" ] && python3 "$trend" || true
}

report() {
    [ -f "$CSV" ] || { echo "[token-metrics] no data yet ($CSV missing) — run a snapshot first."; exit 0; }
    local out="$METRICS_DIR/WEEK-$WEEK.md"
    {
        echo "# Token-efficiency POC metrics — week $WEEK"
        echo ""
        echo "> Generated by \`scripts/token-metrics.sh report\`. Proxies for token spend"
        echo "> (Cursor has no per-turn meter). Pair with \`token-efficiency/RESULTS.md\`."
        echo ""
        echo "| Date | HR savings | Blogs | LLD | Timetable | Solutions | Cron runs |"
        echo "|---|---|---|---|---|---|---|"
        # print rows for this week only, plus keep it simple: all rows
        tail -n +2 "$CSV" | while IFS=, read -r d wk hr b l tt sol cr; do
            echo "| $d | ${hr//\"/} | $b | $l | $tt | $sol | $cr |"
        done
        echo ""
        echo "## Read this alongside"
        echo "- \`orchestration/token-efficiency/RESULTS.md\` — the per-iteration before/after"
        echo "  (file reads, ranged-read %, blob compression, clarify rounds) you fill in by hand."
        echo "- raw Headroom stats per day: \`orchestration/token-efficiency/metrics/raw/<date>.stats.txt\`."
        echo ""
        echo "## POC verdict (fill at week end)"
        echo "- Trend in HR savings: "
        echo "- Iterations that moved the needle: "
        echo "- Keep / drop: "
    } > "$out"
    echo "[token-metrics] wrote $out"
}

case "$ACTION" in
    snapshot|"") snapshot ;;
    report)      report ;;
    *) echo "usage: $0 {snapshot|report}" >&2; exit 2 ;;
esac
